### ISSUE TITLE
Add a timeout option (default 10s) for optimizePeaks

### ISSUE THREAD

**Issue by lpatiny** [mljs/global-spectral-deconvolution#37]
Prevent the system to crash by giving a timeout.

The system should throw if the timeout is reached.

**Comment by jobo322** [comment]
do you have some example in which I can I get inspired?

**Comment by lpatiny** [comment]
You should take the Date.now() at the beginning of the code and then in the optimization loop check if more that 10s was spent in the code. This means that we will still finish an optimization cycle and we can not prevent infinite loops.
