### ISSUE TITLE
Grouping seems not correct

### ISSUE THREAD

**Issue by lpatiny** [mljs/global-spectral-deconvolution#40]
If you are looking at the GSD view of ethyl vinyl ether the grouping seems weird. You have one green peak followed by 2 blue that are further away followed by a green.

![image](https://user-images.githubusercontent.com/1484241/99529901-e21d2880-29a0-11eb-91e8-cf4466b6453a.png)

**Comment by jobo322** [comment]
I think the grouping is ok, there is a small detected peak between those blue peaks. The question now is way the optimization stage disappear this peak

**Comment by lpatiny** [comment]
Ok indeed thanks, I didn't see it. I guess I have a threshold at the level of optimization.
