### ISSUE TITLE
Triplet

### ISSUE THREAD

**Issue by maasencioh** [mljs/global-spectral-deconvolution#6]
Hello, I have a case simple case with triplets for testing and it's not clear to me why it's not taking 3 peaks as suppose to detect

https://runkit.com/maasencioh/576d414c05caad1300fce521

Thanks! :beer:

**Comment by andcastillo** [comment]
Can you make a demo in the visualizer? It will be easier to understand.

**Comment by maasencioh** [comment]
For sure, [here you have it](https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F83e55c39f2601bc912a45f049eb14342%2Fview.json)

**Comment by targos** [comment]
ping @andcastillo
