### ISSUE TITLE
gsd detect negative peaks even when maxCriteria is true

### ISSUE THREAD

**Issue by jobo322** [mljs/global-spectral-deconvolution#92]

**Comment by lpatiny** [comment]
Could you add a failing simple testcase ?

I guess adding a testcase in https://github.com/mljs/global-spectral-deconvolution/blob/master/src/__tests__/gaussian.test.ts

**Comment by jobo322** [comment]
Really, it does not detect the top of the peak, it fails when detecting the minimum values of ddY because for a negative peak with a baseline very close to zero, ddY could have fake minimums. 

![image](https://user-images.githubusercontent.com/12143935/155135841-31e38aef-ec7d-4371-8132-400b7b1294a1.png)

what do you think to calculate the [yThreshold](https://github.com/mljs/global-spectral-deconvolution/blob/master/src/gsd.ts#154) as:

`const yThreshold = minPositiveY + (maxY - minPositiveY ) * minMaxRatio;`

In that way we ensure that only positive internal peaks are the detected.

**Comment by jobo322** [comment]
or it could use absolute values in this step

https://github.com/mljs/global-spectral-deconvolution/blob/master/src/gsd.ts#239
